# Generated by Django 5.2.3 on 2025-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('frequency', models.CharField(choices=[('one-time', 'One-Time'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
